INSERT INTO standards (standard_name, standard_code) VALUES
('Kindergarten Reading: Literature', 'K.RSL'),
('Grade 1 Reading: Literature', '1.RSL'),
('Grade 2 Reading: Literature', '2.RSL'),
('Grade 3 Reading: Literature', '3.RSL'),
('Grade 4 Reading: Literature', '4.RSL'),
('Grade 5 Reading: Literature', '5.RSL'),

('Kindergarten Reading: Informational Text', 'K.RSIT'),
('Grade 1 Reading: Informational Text', '1.RSIT'),
('Grade 2 Reading: Informational Text', '2.RSIT'),
('Grade 3 Reading: Informational Text', '3.RSIT'),
('Grade 4 Reading: Informational Text', '4.RSIT'),
('Grade 5 Reading: Informational Text', '5.RSIT'),

('Kindergarten Reading: Foundational Skills', 'K.RSFS'),
('Grade 1 Reading: Foundational Skills', '1.RSFS'),
('Grade 2 Reading: Foundational Skills', '2.RSFS'),
('Grade 3 Reading: Foundational Skills', '3.RSFS'),
('Grade 4 Reading: Foundational Skills', '4.RSFS'),
('Grade 5 Reading: Foundational Skills', '5.RSFS')   
ON CONFLICT (standard_code) DO NOTHING;

-- RSL
INSERT INTO proficiencies (proficiency_name, standard_id, proficiency_code) VALUES
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLRRLTC')
ON CONFLICT (proficiency_code) DO NOTHING;

-- RSIT
INSERT INTO proficiencies (proficiency_name, standard_id, proficiency_code) VALUES
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSITKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSICS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSIIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSIRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSIKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSICS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSIIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSIRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSIKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSICS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSIIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSIRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSIKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSICS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSIIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSIRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSIKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSICS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSIIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSIRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSIKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSICS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSIIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSIRRLTC')
ON CONFLICT (proficiency_code) DO NOTHING;

-- RSFS
INSERT INTO proficiencies (proficiency_name, standard_id, proficiency_code) VALUES
('Print Concepts', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSFS'), 'K.RSFSPC'),
('Phonological Awareness', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSFS'), 'K.RSFSPA'),
('Phonics and Word Recognition', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSFS'), 'K.RSFPWR'),
('Fluency', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSFS'), 'K.RSFF'),
('Print Concepts', (SELECT standard_id FROM standards WHERE standard_code = '1.RSFS'), '1.RSFSPC'),
('Phonological Awareness', (SELECT standard_id FROM standards WHERE standard_code = '1.RSFS'), '1.RSFSPA'),
('Phonics and Word Recognition', (SELECT standard_id FROM standards WHERE standard_code = '1.RSFS'), '1.RSFPWR'),
('Fluency', (SELECT standard_id FROM standards WHERE standard_code = '1.RSFS'), '1.RSFF'),
('Print Concepts', (SELECT standard_id FROM standards WHERE standard_code = '2.RSFS'), '2.RSFSPC'),
('Phonological Awareness', (SELECT standard_id FROM standards WHERE standard_code = '2.RSFS'), '2.RSFSPA'),
('Phonics and Word Recognition', (SELECT standard_id FROM standards WHERE standard_code = '2.RSFS'), '2.RSFPWR'),
('Fluency', (SELECT standard_id FROM standards WHERE standard_code = '2.RSFS'), '2.RSFF'),
('Print Concepts', (SELECT standard_id FROM standards WHERE standard_code = '3.RSFS'), '3.RSFSPC'),
('Phonological Awareness', (SELECT standard_id FROM standards WHERE standard_code = '3.RSFS'), '3.RSFSPA'),
('Phonics and Word Recognition', (SELECT standard_id FROM standards WHERE standard_code = '3.RSFS'), '3.RSFPWR'),
('Fluency', (SELECT standard_id FROM standards WHERE standard_code = '3.RSFS'), '3.RSFF'),
('Print Concepts', (SELECT standard_id FROM standards WHERE standard_code = '4.RSFS'), '4.RSFSPC'),
('Phonological Awareness', (SELECT standard_id FROM standards WHERE standard_code = '4.RSFS'), '4.RSFSPA'),
('Phonics and Word Recognition', (SELECT standard_id FROM standards WHERE standard_code = '4.RSFS'), '4.RSFPWR'),
('Fluency', (SELECT standard_id FROM standards WHERE standard_code = '4.RSFS'), '4.RSFF'),
('Print Concepts', (SELECT standard_id FROM standards WHERE standard_code = '5.RSFS'), '5.RSFSPC'),
('Phonological Awareness', (SELECT standard_id FROM standards WHERE standard_code = '5.RSFS'), '5.RSFSPA'),
('Phonics and Word Recognition', (SELECT standard_id FROM standards WHERE standard_code = '5.RSFS'), '5.RSFPWR'),
('Fluency', (SELECT standard_id FROM standards WHERE standard_code = '5.RSFS'), '5.RSFF')
ON CONFLICT (proficiency_code) DO NOTHING;

-- Kindergarten start nodes self-reference prev.
-- Grade 5 end nodes self-reference next.

-- RSL — Reading: Literature
INSERT INTO skill_sets (skill_set_code, prev_skill_set_code, next_skill_set_code, proficiency_id, description) VALUES
('K.RSLKID.1', 'K.RSLKID.1', 'K.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLKID'),
 'With prompting and support, ask and answer questions about key details in a text.'),
('K.RSLKID.2', 'K.RSLKID.1', 'K.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLKID'),
 'With prompting and support, retell familiar stories, including key details.'),
('K.RSLKID.3', 'K.RSLKID.2', 'K.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLKID'),
 'With prompting and support, identify characters, settings, and major events in a story.'),
('K.RSLCS.4', 'K.RSLKID.3', 'K.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLCS'),
 'Ask and answer questions about unknown words in a text.'),
('K.RSLCS.5', 'K.RSLCS.4', 'K.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLCS'),
 'Recognize common types of texts (e.g., storybooks, poems).'),
('K.RSLCS.6', 'K.RSLCS.5', 'K.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLCS'),
 'With prompting and support, name the author and illustrator of a story and define the role of each in telling the story.'),
('K.RSLIKI.7', 'K.RSLCS.6', 'K.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLIKI'),
 'With prompting and support, describe the relationship between illustrations and the story in which they appear (e.g., what moment in a story an illustration depicts).'),
('K.RSLIKI.9', 'K.RSLIKI.7', 'K.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLIKI'),
 'With prompting and support, compare and contrast the adventures and experiences of characters in familiar stories.'),
('K.RSLRRLTC.10', 'K.RSLIKI.9', '1.RSLKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLRRLTC'),
 'Actively engage in group reading activities with purpose and understanding.'),
('1.RSLKID.1', 'K.RSLRRLTC.10', '1.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLKID'),
 'Ask and answer questions about key details in a text.'),
('1.RSLKID.2', '1.RSLKID.1', '1.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLKID'),
 'Retell stories, including key details, and demonstrate understanding of their central message or lesson.'),
('1.RSLKID.3', '1.RSLKID.2', '1.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLKID'),
 'Describe characters, settings, and major events in a story, using key details.'),
('1.RSLCS.4', '1.RSLKID.3', '1.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLCS'),
 'Identify words and phrases in stories or poems that suggest feelings or appeal to the senses.'),
('1.RSLCS.5', '1.RSLCS.4', '1.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLCS'),
 'Explain major differences between books that tell stories and books that give information, drawing on a wide reading of a range of text types.'),
('1.RSLCS.6', '1.RSLCS.5', '1.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLCS'),
 'Identify who is telling the story at various points in a text.'),
('1.RSLIKI.7', '1.RSLCS.6', '1.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLIKI'),
 'Use illustrations and details in a story to describe its characters, setting, or events.'),
('1.RSLIKI.9', '1.RSLIKI.7', '1.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLIKI'),
 'Compare and contrast the adventures and experiences of characters in stories.'),
('1.RSLRRLTC.10', '1.RSLIKI.9', '2.RSLKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLRRLTC'),
 'With prompting and support, read prose and poetry of appropriate complexity for grade 1.'),
('2.RSLKID.1', '1.RSLRRLTC.10', '2.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLKID'),
 'Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.'),
('2.RSLKID.2', '2.RSLKID.1', '2.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLKID'),
 'Recount stories, including fables and folktales from diverse cultures, and determine their central message, lesson, or moral.'),
('2.RSLKID.3', '2.RSLKID.2', '2.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLKID'),
 'Describe how characters in a story respond to major events and challenges.'),
('2.RSLCS.4', '2.RSLKID.3', '2.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLCS'),
 'Describe how words and phrases (e.g., regular beats, alliteration, rhymes, repeated lines) supply rhythm and meaning in a story, poem, or song.'),
('2.RSLCS.5', '2.RSLCS.4', '2.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLCS'),
 'Describe the overall structure of a story, including describing how the beginning introduces the story and the ending concludes the action.'),
('2.RSLCS.6', '2.RSLCS.5', '2.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLCS'),
 'Acknowledge differences in the points of view of characters, including by speaking in a different voice for each character when reading dialogue aloud.'),
('2.RSLIKI.7', '2.RSLCS.6', '2.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLIKI'),
 'Use information gained from the illustrations and words in a print or digital text to demonstrate understanding of its characters, setting, or plot.'),
('2.RSLIKI.9', '2.RSLIKI.7', '2.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLIKI'),
 'Compare and contrast two or more versions of the same story (e.g., Cinderella stories) by different authors or from different cultures.'),
('2.RSLRRLTC.10', '2.RSLIKI.9', '3.RSLKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLRRLTC'),
 'By the end of the year, read and comprehend literature, including stories and poetry, in the grades 2-3 text complexity band proficiently, with scaffolding as needed at the high end of the range.'),
('3.RSLKID.1', '2.RSLRRLTC.10', '3.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLKID'),
 'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.'),
('3.RSLKID.2', '3.RSLKID.1', '3.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLKID'),
 'Recount stories, including fables, folktales, and myths from diverse cultures; determine the central message, lesson, or moral and explain how it is conveyed through key details in the text.'),
('3.RSLKID.3', '3.RSLKID.2', '3.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLKID'),
 'Describe characters in a story (e.g., their traits, motivations, or feelings) and explain how their actions contribute to the sequence of events.'),
('3.RSLCS.4', '3.RSLKID.3', '3.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLCS'),
 'Determine the meaning of words and phrases as they are used in a text, distinguishing literal from non literal language.'),
('3.RSLCS.5', '3.RSLCS.4', '3.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLCS'),
 'Refer to parts of stories, dramas, and poems when writing or speaking about a text, using terms such as chapter, scene, and stanza; describe how each successive part builds on earlier sections.'),
('3.RSLCS.6', '3.RSLCS.5', '3.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLCS'),
 'Distinguish their own point of view from that of the narrator or those of the characters.'),
('3.RSLIKI.7', '3.RSLCS.6', '3.RSLIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLIKI'),
 'Use information gained from illustrations (e.g., maps, photographs) and the words in a text to demonstrate understanding of the text (e.g., where, when, why, and how key events occur).'),
('3.RSLIKI.8', '3.RSLCS.8', '3.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLIKI'),
 'Describe the logical connection between particular sentences and paragraphs in a text(e.g., comparison, cause/effect, first/second / third in a sequence).'),
('3.RSLIKI.9', '3.RSLIKI.8', '3.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLIKI'),
 'Compare and contrast the most important points and key details presented in two texts on the same topic.'),
('3.RSLRRLTC.10', '3.RSLIKI.9', '4.RSLKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLRRLTC'),
 'By the end of the year, read and comprehend informational texts, including history/social studies, science, and technical texts, at the high end of the grades 2-3 text complexity band independently and proficiently.'),
('4.RSLKID.1', '3.RSLRRLTC.10', '4.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLKID'),
 'Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.'),
('4.RSLKID.2', '4.RSLKID.1', '4.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLKID'),
 'Determine a theme of a story, drama, or poem from details in the text; summarize the text.'),
('4.RSLKID.3', '4.RSLKID.2', '4.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLKID'),
 'Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text (e.g., a character''s thoughts, words, or actions).'),
('4.RSLCS.4', '4.RSLKID.3', '4.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLCS'),
 'Determine the meaning of words and phrases as they are used in a text, including those that allude to significant characters found in mythology (e.g., Herculean).'),
('4.RSLCS.5', '4.RSLCS.4', '4.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLCS'),
 'Explain major differences between poems, drama, and prose, and refer to the structural elements of poems (e.g., verse, rhythm, meter) and drama (e.g., casts of characters, settings, descriptions, dialogue, stage directions) when writing or speaking about a text.'),
('4.RSLCS.6', '4.RSLCS.5', '4.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLCS'),
 'Compare and contrast the point of view from which different stories are narrated, including the difference between first- and third-person narrations.'),
('4.RSLIKI.7', '4.RSLCS.6', '4.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLIKI'),
 'Make connections between the text of a story or drama and a visual or oral presentation of the text, identifying where each version reflects specific descriptions and directions in the text.'),
('4.RSLIKI.9', '4.RSLIKI.7', '4.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLIKI'),
 'Compare and contrast the treatment of similar themes and topics (e.g., opposition of good and evil) and patterns of events (e.g., the quest) in stories, myths, and traditional literature from different cultures.'),
('4.RSLRRLTC.10', '4.RSLIKI.9', '5.RSLKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLRRLTC'),
 'By the end of the year, read and comprehend literature, including stories, dramas, and poetry, in the grades 4-5 text complexity band proficiently, with scaffolding as needed at the high end of the range.'),
('5.RSLKID.1', '4.RSLRRLTC.10', '5.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLKID'),
 'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.'),
('5.RSLKID.2', '5.RSLKID.1', '5.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLKID'),
 'Determine a theme of a story, drama, or poem from details in the text, including how characters in a story or drama respond to challenges or how the speaker in a poem reflects upon a topic; summarize the text.'),
('5.RSLKID.3', '5.RSLKID.2', '5.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLKID'),
 'Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text (e.g., how characters interact).'),
('5.RSLCS.4', '5.RSLKID.3', '5.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLCS'),
 'Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes.'),
('5.RSLCS.5', '5.RSLCS.4', '5.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLCS'),
 'Explain how a series of chapters, scenes, or stanzas fits together to provide the overall structure of a particular story, drama, or poem.'),
('5.RSLCS.6', '5.RSLCS.5', '5.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLCS'),
 'Describe how a narrator''s or speaker''s point of view influences how events are described.'),
('5.RSLIKI.7', '5.RSLCS.6', '5.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLIKI'),
 'Analyze how visual and multimedia elements contribute to the meaning, tone, or beauty of a text (e.g., graphic novel, multimedia presentation of fiction, folktale, myth, poem).'),
('5.RSLIKI.9', '5.RSLIKI.7', '5.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLIKI'),
 'Compare and contrast stories in the same genre (e.g., mysteries and adventure stories) on their approaches to similar themes and topics.'),
('5.RSLRRLTC.10', '5.RSLIKI.9', '5.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLRRLTC'),
 'By the end of the year, read and comprehend literature, including stories, dramas, and poetry, at the high end of the grades 4-5 text complexity band independently and proficiently.')
ON CONFLICT (skill_set_code) DO NOTHING;

-- RSIT — Reading: Informational Text
INSERT INTO skill_sets (skill_set_code, prev_skill_set_code, next_skill_set_code, proficiency_id, description) VALUES
('K.RSITKID.1', 'K.RSITKID.1', 'K.RSITKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITKID'), 
 'With prompting and support, ask and answer questions about key details in a text.'),
('K.RSITKID.2', 'K.RSITKID.1', 'K.RSITKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITKID'), 
 'With prompting and support, identify the main topic and retell key details of a text.'),
('K.RSITKID.3', 'K.RSITKID.2', 'K.RSICS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITKID'), 
 'With prompting and support, describe the connection between two individuals, events, ideas, or pieces of information in a text.'),
('K.RSICS.4', 'K.RSITKID.3', 'K.RSICS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSICS'), 
 'With prompting and support, ask and answer questions about unknown words in a text.'),
('K.RSICS.5', 'K.RSICS.4', 'K.RSICS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSICS'), 
 'Identify the front cover, back cover, and title page of a book.'),
('K.RSICS.6', 'K.RSICS.5', 'K.RSIIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSICS'), 
 'Name the author and illustrator of a text and define the role of each in presenting the ideas or information in a text. '),
('K.RSIIKI.7', 'K.RSICS.6', 'K.RSIIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSIIKI'), 
 'With prompting and support, describe the relationship between illustrations and the text in which they appear (e.g., what person, place, thing, or idea in the text an illustration depicts).'),
('K.RSIIKI.8', 'K.RSIIKI.7', 'K.RSIIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSIIKI'), 
 'With prompting and support, identify the reasons an author gives to support points in a text.'),
('K.RSIIKI.9', 'K.RSIIKI.8', 'K.RSIRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSIIKI'), 
 'With prompting and support, identify basic similarities in and differences between two texts on the same topic (e.g., in illustrations, descriptions, or procedures).'),
('K.RSIRRLTC.10', 'K.RSIIKI.9', '1.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSIRRLTC'), 
 'Actively engage in groqp reading activities with purpose and understanding.'),
('1.RSITKID.1', 'K.RSIRRLTC.10', '1.RSITKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITKID'), 
 'Ask and answer questions about key details in a text.'),
('1.RSITKID.2', '1.RSITKID.1', '1.RSITKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITKID'), 
 'Identify the main topic and retell key details of a text'),
('1.RSITKID.3', '1.RSITKID.2', '1.RSICS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITKID'), 
 'Describe the connection between two individuals, events, ideas, or pieces of information in a text.'),
('1.RSICS.4', '1.RSITKID.3', '1.RSICS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSICS'), 
 'Ask and answer questions to help determine or clarify the meaning of words and phrases in a text.'),
('1.RSICS.5', '1.RSICS.4', '1.RSICS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSICS'), 
 'Know and use various text features (e.g., headings, tables of contents, glossaries, electronic menus, icons) to locate key facts or information in a text.'),
('1.RSICS.6', '1.RSICS.5', '1.RSIIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSICS'), 
 'Distinguish between information provided by pictures or other illustrations and information provided by the words in a text.'),
('1.RSIIKI.7', '1.RSICS.6', '1.RSIIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSIIKI'), 
 'Use the illustrations and details in a text to describe its key ideas. '),
('1.RSIIKI.8', '1.RSIIKI.7', '1.RSIIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSIIKI'), 
 'Identify the reasons an author gives to support points in a text'),
('1.RSIIKI.9', '1.RSIIKI.8', '1.RSIRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSIIKI'), 
 'Identify basic simalarities in and differences between two texts on the same topic (e.g., in illustrations, descriptions, or procedures). '),
('1.RSIRRLTC.10', '1.RSIIKI.9', '1.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSIRRLTC'), 
 'With prompting and support, read informational texts appropriately complex for grade 1.'),
('2.RSITKID.1', '1.RSIRRLTC.10', '2.RSITKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITKID'), 
 'Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.'),
('2.RSITKID.2', '2.RSITKID.1', '2.RSITKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITKID'), 
 'Identify the main topic of a multiparagraph text as well as the focus of specific paragraphs within the text.'),
('2.RSITKID.3', '2.RSITKID.2', '2.RSICS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITKID'), 
 'Describe the connection between a series of historical events, scientific ideas or boncepts, or steps in technical procedures in a text'),
('2.RSICS.4', '2.RSITKID.3', '2.RSICS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSICS'), 
 'Determine the meaning of words and phrases in a text relevant to a grade 2 topic or subject area'),
('2.RSICS.5', '2.RSICS.4', '2.RSICS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSICS'), 
 'Know and use various text features (e.g., captions, bold print, subheadings, glossaries, indexes, electronic menus, icons) to locate key facts or information in a text efficiently.'),
('2.RSICS.6', '2.RSICS.5', '2.RSIIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSICS'), 
 'Identify the main purpose of a text, including what the author wants to answer, explain, or describe. '),
('2.RSIIKI.7', '2.RSICS.6', '2.RSIIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSIIKI'), 
 'Explain how specific images (e.g., a diagram showing how a machine works) contribute to and clarify a text.'),
('2.RSIIKI.8', '2.RSIIKI.7', '2.RSIIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSIIKI'), 
 'Describe how reasons support specific points the author makes in a text.'),
('2.RSIIKI.9', '2.RSIIKI.8', '2.RSIRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSIIKI'), 
 ' Compare and contrast the most important points presented by two texts on the same tophc. Compare and contrast the most important points presented by two texts on the same topic.'),
('2.RSIRRLTC.10', '2.RSIIKI.9', '2.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSIRRLTC'), 
 ' By the end of year, read and comprehend informational texts, including history/social studies, science, and technical texts, in the grades 2–3 text complexity band proficiently, with scaffolding as needed at the high end of the range.'),
('3.RSITKID.1', '3.RSIRRLTC.10', '3.RSITKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITKID'), 
 'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers. '),
('3.RSITKID.2', '3.RSITKID.1', '3.RSITKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITKID'), 
 'Determine the main idea of a text, recount the key details and explain how they support the main idea. '),
('3.RSITKID.3', '3.RSITKID.2', '3.RSICS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITKID'), 
 'Describe the relationship between a series of historical events, scientific ideas or concepts, or steps in technical procedures in a text, using language that pertains to time, sequence, and cause/effect. '),
('3.RSICS.4', '3.RSITKID.3', '3.RSICS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSICS'), 
 'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 3 topic or subject area.'),
('3.RSICS.5', '3.RSICS.4', '3.RSICS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSICS'), 
 'Use text features and search tools (e.g. key words, sidebars, hyperlinks) to locate information relevant to a given topic efficiently. '),
('3.RSICS.6', '3.RSICS.5', '3.RSIIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3  .RSICS'), 
 'Distinguish their own point of view from that of the author of a text.'),
('3.RSIIKI.7', '3.RSICS.6', '3.RSIIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSIIKI'), 
 'Use information gained from illustrations (e.g., maps, photographs) and the words in a text to demonstrate understanding of the text (e.g. where, when, why and how key events occur).'),
('3.RSIIKI.8', '3.RSIIKI.7', '3.RSIIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSIIKI'), 
 'Describe the logical connection between particular sentences and paragraphs in a text (e.g., comparison, cause/effect, first/second/third in a sequencd). '),
('3.RSIIKI.9', '3.RSIIKI.8', '3.RSIRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSIIKI'), 
 'Compare and contrast the most important points and key details presented in two texts on the same topic.'),
('3.RSIRRLTC.10', '3.RSIIKI.9', '3.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSIRRLTC'), 
 'By the end of the year, read and comprehend informational texts, including history/social studies, science, and technical texts, at the high end of the grades 2.-3 text complexity band independently and proficiently.'),
('4.RSITKID.1', '4.RSIRRLTC.10', '4.RSITKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITKID'), 
 'Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text. '),
('4.RSITKID.2', '4.RSITKID.1', '4.RSITKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITKID'), 
 'Determine the main idea of a text and explain how it is supported by key details; summarize the text.'),
('4.RSITKID.3', '4.RSITKID.2', '4.RSICS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITKID'), 
 'Explain evens, procedures, ideas, or concepts in a historical, scientific, or technical text, including what happened and why, based on specific information in the text.'),
('4.RSICS.4', '4.RSITKID.3', '4.RSICS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSICS'), 
 'Determine the meaning of general academic and domain-specific words or phrases in a text relevant to a grade 4 topic or subject area. '),
('4.RSICS.5', '4.RSICS.4', '4.RSICS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSICS'), 
 'Describe the overall structure (e.g., chronology, comparison, cause/effect, problem/solution) of events, ideas, concepts, or information in a text or part of a text.'),
('4.RSICS.6', '4.RSICS.5', '4.RSIIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSICS'), 
 'Compare and contrast a firsthand and secondhand account of the same event or topic; describe the differences in focus and the information provided.'),
('4.RSIIKI.7', '4.RSICS.6', '4.RSIIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSIIKI'), 
 'Interpret information presented visually, orally, or quantitatively (e.g., in charts, graphs, diagrams, time lines, animations, or interactive elements on Web ages)and explain how the information contributes to an understanding of the text in which it appears.'),
('4.RSIIKI.8', '4.RSIIKI.7', '4.RSIIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSIIKI'), 
 'Explain how an author uses reasons and evidence do support particular points in a text.'),
('4.RSIIKI.9', '4.RSIIKI.8', '4.RSIRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSIIKI'), 
 'Integrate information from two texts on the same topic in order to write or speak about the subject knowledgeably.'),
('4.RSIRRLTC.10', '4.RSIIKI.9', '4.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSIRRLTC'), 
 'By the end of year, read and comprehend informational texts, including history/social studies, science, and technical texts, in the grades 4-5 text complexity band proficiently, with scaffolding as needed at the high end of the range.'),
('5.RSITKID.1', '5.RSITKID.1', '5.RSITKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITKID'), 
 'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.'),
('5.RSITKID.2', '5.RSITKID.1', '5.RSITKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITKID'), 
 'Determine two or more main ideas of a text and explain how they are supported by key details, summarize the text.'),
('5.RSITKID.3', '5.RSITKID.2', '5.RSICS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITKID'), 
 'Explain the relationships or interactions between two or more individuals, events, ideas, or concepts in a historical, scientific, or technical text based on specific information in the text.'),
('5.RSICS.4', '5.RSITKID.3', '5.RSICS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSICS'), 
 'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 5 topic or subject area.'),
('5.RSICS.5', '5.RSICS.4', '5.RSICS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSICS'), 
 'Compare and contrast the overall structure (e.g. chronology, comparison, cause/effect, problem/solution) of events, ideas, concepts, or information in two or more texts.'),
('5.RSICS.6', '5.RSICS.5', '5.RSITKID.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSICS'), 
 'Analyze multiple accounts of the same event or topic, noting important similarities and differences in the point of view they represent.'),
('5.RSIIKI.7', '5.RSICS.6', '5.RSIIKI.8',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSIIKI'), 
 'Draw on information from multiple print or digital sources, demonstrating the ability to locate an answer to a question quickly or to solve a problem efficiently.'),
('5.RSIIKI.8', '5.RSIIKI.7', '5.RSIIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSIIKI'), 
 'Explain how an author uses reasons and evidence to support particular points in a text, identifying which reasons and evidence support which point(s).'),
('5.RSIIKI.9', '5.RSIIKI.8', '5.RSIRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSIIKI'), 
 'Integrate information from several texts on the same topic to write or speak about subjects knowledgeably.'),
('5.RSIRRLTC.10', '5.RSIIKI.9', '5.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSIRRLTC'), 
 'By the end of the year, read and comprehend informational texts, including history/social studies, science, and technical texts, at the high end of the grades 4-5 text complexity band independently and proficiently.')
ON CONFLICT (skill_set_code) DO NOTHING;

-- RSF — Reading: Foundational Skills
INSERT INTO skill_sets (skill_set_code, prev_skill_set_code, next_skill_set_code, proficiency_id, description) VALUES
('K.RSFSPC.1', 'K.RSFSPC.1', 'K.RSFSPA.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFSPC'), 
 'Demonstrate understanding of the organization and basic features of print.'),
('K.RSFSPA.2', 'K.RSFSPC.1', 'K.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFSPA'), 
 'Demonstrate understanding of spoken words, syllables, and sounds (phonemes).'),
('K.RSFPWR.3', 'K.RSFSPA.2', 'K.RSFPF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFPWR'), 
 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
('K.RSFPF.4', 'K.RSFPWR.3', '1.RSFSPC.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFPF'), 
 'Read emergent-reader texts with purpose and understanding.'),
('1.RSFSPC.1', '1.RSFSPC.1', '1.RSFSPA.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFSPC'), 
 'Demonstrate understanding of the organization and basic features of print.'),
('1.RSFSPA.2', '1.RSFSPC.1', '1.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFSPA'), 
 'Demonstrate understanding of spoken words, syllables, and sounds (phonemes).'),
('1.RSFPWR.3', '1.RSFSPA.2', '1.RSFPF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFPWR'), 
 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
('1.RSFPF.4', '1.RSFPWR.3', '2.RSFSPC.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFPF'), 
 ' Read with sufficient accuracy and fluency to support comprehension'),
('2.RSFPWR.3', '1.RSFPF.4', '2.RSFPF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSFPWR'), 
 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
('2.RSFPF.4', '2.RSFPWR.3', '3.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSFPF'), 
 'Read with sufficient accuracy and fluency to support comprehension'),
('3.RSFPWR.3', '2.RSFPF.4', '3.RSFPF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSFPWR'), 
 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
('3.RSFPF.4', '3.RSFPWR.3', '4.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSFPF'), 
 'Read with sufficient accuracy and fluency to support comprehension'),
('4.RSFPWR.3', '3.RSFPF.4', '4.RSFPF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSFPWR'), 
 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
('4.RSFPF.4', '4.RSFPWR.3', '5.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSFPF'), 
 'Read with sufficient accuracy and fluency to support comprehension'),
('5.RSFPWR.3', '4.RSFPF.4', '5.RSFPF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSFPWR'), 
 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
('5.RSFPF.4', '5.RSFPWR.3', '5.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSFPF'), 
 'Read with sufficient accuracy and fluency to support comprehension')
ON CONFLICT (skill_set_code) DO NOTHING;
