INSERT INTO standards (standard_name, standard_code) VALUES
-- Literature Standards (RL)
('Kindergarten Reading: Literature', 'K.RSL'),
('Grade 1 Reading: Literature', '1.RSL'),
('Grade 2 Reading: Literature', '2.RSL'),
('Grade 3 Reading: Literature', '3.RSL'),
('Grade 4 Reading: Literature', '4.RSL'),
('Grade 5 Reading: Literature', '5.RSL'),

-- Informational Text Standards (RI)
('', 'K.RSIT'),
('', '1.RSIT'),
('', '2.RSIT'),
('', '3.RSIT'),
('', '4.RSIT'),
('', '5.RSIT'),

-- Foundational Skills Standards (RF)
('', 'K.RSF'),
('', '1.RSF'),
('', '2.RSF'),
('', '3.RSF'),
('', '4.RSF'),
('', '5.RSF')
ON CONFLICT (standard_code) DO NOTHING;

-- RSL
INSERT INTO proficiencies (proficiency_name, standard_id, proficiency_code) VALUES
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSL'), 'K.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '1.RSL'), '1.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '2.RSL'), '2.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '3.RSL'), '3.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '4.RSL'), '4.RSLRRLTC'),
('Key Ideas and Details', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLKID'),
('Craft and Structure', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLCS'),
('Integration of Knowledge and Ideas', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLIKI'),
('Range of Reading and Text Complexity', (SELECT standard_id FROM standards WHERE standard_code = '5.RSL'), '5.RSLRRLTC')
ON CONFLICT (proficiency_code) DO NOTHING;

-- RSIT
INSERT INTO proficiencies (proficiency_name, standard_id, proficiency_code) VALUES
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSITKID'),
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSITCS'),
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSITIKI'),
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSIT'), 'K.RSITRRLTC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSITKID'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSITCS'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSITIKI'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSIT'), '1.RSITRRLTC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSITKID'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSITCS'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSITIKI'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSIT'), '2.RSITRRLTC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSITKID'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSITCS'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSITIKI'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSIT'), '3.RSITRRLTC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSITKID'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSITCS'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSITIKI'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSIT'), '4.RSITRRLTC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSITKID'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSITCS'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSITIKI'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSIT'), '5.RSITRRLTC')
ON CONFLICT (proficiency_code) DO NOTHING;

-- RSF
INSERT INTO proficiencies (proficiency_name, standard_id, proficiency_code) VALUES
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSF'), 'K.RSFSPC'),
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSF'), 'K.RSFSPA'),
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSF'), 'K.RSFPWR'),
('', (SELECT standard_id FROM standards WHERE standard_code = 'K.RSF'), 'K.RSFF'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSF'), '1.RSFSPC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSF'), '1.RSFSPA'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSF'), '1.RSFPWR'),
('', (SELECT standard_id FROM standards WHERE standard_code = '1.RSF'), '1.RSFF'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSF'), '2.RSFSPC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSF'), '2.RSFSPA'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSF'), '2.RSFPWR'),
('', (SELECT standard_id FROM standards WHERE standard_code = '2.RSF'), '2.RSFF'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSF'), '3.RSFSPC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSF'), '3.RSFSPA'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSF'), '3.RSFPWR'),
('', (SELECT standard_id FROM standards WHERE standard_code = '3.RSF'), '3.RSFF'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSF'), '4.RSFSPC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSF'), '4.RSFSPA'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSF'), '4.RSFPWR'),
('', (SELECT standard_id FROM standards WHERE standard_code = '4.RSF'), '4.RSFF'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSF'), '5.RSFSPC'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSF'), '5.RSFSPA'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSF'), '5.RSFPWR'),
('', (SELECT standard_id FROM standards WHERE standard_code = '5.RSF'), '5.RSFF')
ON CONFLICT (proficiency_code) DO NOTHING;

-- Kindergarten start nodes self-reference prev.
-- Grade 5 end nodes self-reference next.
-- 2.RSLIKI.8 excluded — RL.2.8 is not applicable to literature.

-- RSL — Reading: Literature
INSERT INTO skill_sets (skill_set_code, prev_skill_set_code, next_skill_set_code, proficiency_id, description) VALUES
('K.RSLKID.1', 'K.RSLKID.1', 'K.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLKID'),
 'With prompting and support, ask and answer questions about key details in a text.'),
('1.RSLKID.1', 'K.RSLKID.1', '1.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLKID'),
 'Ask and answer questions about key details in a text.'),
('2.RSLKID.1', '1.RSLKID.1', '2.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLKID'),
 'Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.'),
('3.RSLKID.1', '2.RSLKID.1', '3.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLKID'),
 'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.'),
('4.RSLKID.1', '3.RSLKID.1', '4.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLKID'),
 'Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.'),
('5.RSLKID.1', '4.RSLKID.1', '5.RSLKID.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLKID'),
 'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.'),
('K.RSLKID.2', 'K.RSLKID.1', 'K.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLKID'),
 'With prompting and support, retell familiar stories, including key details.'),
('1.RSLKID.2', '1.RSLKID.1', '1.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLKID'),
 'Retell stories, including key details, and demonstrate understanding of their central message or lesson.'),
('2.RSLKID.2', '2.RSLKID.1', '2.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLKID'),
 'Recount stories, including fables and folktales from diverse cultures, and determine their central message, lesson, or moral.'),
('3.RSLKID.2', '3.RSLKID.1', '3.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLKID'),
 'Recount stories, including fables, folktales, and myths from diverse cultures; determine the central message, lesson, or moral and explain how it is conveyed through key details in the text.'),
('4.RSLKID.2', '4.RSLKID.1', '4.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLKID'),
 'Determine a theme of a story, drama, or poem from details in the text; summarize the text.'),
('5.RSLKID.2', '5.RSLKID.1', '5.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLKID'),
 'Determine a theme of a story, drama, or poem from details in the text, including how characters in a story or drama respond to challenges or how the speaker in a poem reflects upon a topic; summarize the text.'),
('K.RSLKID.3', 'K.RSLKID.2', 'K.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLKID'),
 'With prompting and support, identify characters, settings, and major events in a story.'),
('1.RSLKID.3', '1.RSLKID.2', '1.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLKID'),
 'Describe characters, settings, and major events in a story, using key details.'),
('2.RSLKID.3', '2.RSLKID.2', '2.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLKID'),
 'Describe how characters in a story respond to major events and challenges.'),
('3.RSLKID.3', '3.RSLKID.2', '4.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLKID'),
 'Describe characters in a story (e.g., their traits, motivations, or feelings) and explain how their actions contribute to the sequence of events.'),
('4.RSLKID.3', '4.RSLKID.2', '5.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLKID'),
 'Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text (e.g., a character''s thoughts, words, or actions).'),
('5.RSLKID.3', '5.RSLKID.2', '5.RSLKID.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLKID'),
 'Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text (e.g., how characters interact).'),
('K.RSLCS.4', 'K.RSLKID.3', 'K.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLCS'),
 'Ask and answer questions about unknown words in a text.'),
('1.RSLCS.4', '1.RSLKID.3', '2.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLCS'),
 'Identify words and phrases in stories or poems that suggest feelings or appeal to the senses.'),
('2.RSLCS.4', '1.RSLCS.4', '3.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLCS'),
 'Describe how words and phrases (e.g., regular beats, alliteration, rhymes, repeated lines) supply rhythm and meaning in a story, poem, or song.'),
('3.RSLCS.4', '3.RSLKID.1', '4.RSLCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLCS'),
 'Determine the meaning of words and phrases as they are used in a text, distinguishing literal from non literal language.'),
('4.RSLCS.4', '3.RSLCS.4', '4.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLCS'),
 'Determine the meaning of words and phrases as they are used in a text, including those that allude to significant characters found in mythology (e.g., Herculean).'),
('5.RSLCS.4', '4.RSLCS.4', '5.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLCS'),
 'Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes.'),
('K.RSLCS.5', 'K.RSLCS.4', '1.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLCS'),
 'Recognize common types of texts (e.g., storybooks, poems).'),
('1.RSLCS.5', 'K.RSLCS.5', '2.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLCS'),
 'Explain major differences between books that tell stories and books that give information, drawing on a wide reading of a range of text types.'),
('2.RSLCS.5', '1.RSLCS.5', '3.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLCS'),
 'Describe the overall structure of a story, including describing how the beginning introduces the story and the ending concludes the action.'),
('3.RSLCS.5', '2.RSLCS.5', '4.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLCS'),
 'Refer to parts of stories, dramas, and poems when writing or speaking about a text, using terms such as chapter, scene, and stanza; describe how each successive part builds on earlier sections.'),
('4.RSLCS.5', '4.RSLCS.4', '5.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLCS'),
 'Explain major differences between poems, drama, and prose, and refer to the structural elements of poems (e.g., verse, rhythm, meter) and drama (e.g., casts of characters, settings, descriptions, dialogue, stage directions) when writing or speaking about a text.'),
('5.RSLCS.5', '4.RSLCS.5', '5.RSLCS.5',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLCS'),
 'Explain how a series of chapters, scenes, or stanzas fits together to provide the overall structure of a particular story, drama, or poem.'),
('K.RSLCS.6', 'K.RSLKID.1', '1.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLCS'),
 'With prompting and support, name the author and illustrator of a story and define the role of each in telling the story.'),
('1.RSLCS.6', 'K.RSLCS.6', '2.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLCS'),
 'Identify who is telling the story at various points in a text.'),
('2.RSLCS.6', '1.RSLCS.6', '3.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLCS'),
 'Acknowledge differences in the points of view of characters, including by speaking in a different voice for each character when reading dialogue aloud.'),
('3.RSLCS.6', '2.RSLCS.6', '4.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLCS'),
 'Distinguish their own point of view from that of the narrator or those of the characters.'),
('4.RSLCS.6', '3.RSLCS.6', '5.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLCS'),
 'Compare and contrast the point of view from which different stories are narrated, including the difference between first- and third-person narrations.'),
('5.RSLCS.6', '4.RSLCS.6', '5.RSLCS.6',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLCS'),
 'Describe how a narrator''s or speaker''s point of view influences how events are described.'),
('K.RSLIKI.7', 'K.RSLKID.3', 'K.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLIKI'),
 'With prompting and support, describe the relationship between illustrations and the story in which they appear (e.g., what moment in a story an illustration depicts).'),
('1.RSLIKI.7', 'K.RSLIKI.7', '1.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLIKI'),
 'Use illustrations and details in a story to describe its characters, setting, or events.'),
('2.RSLIKI.7', '2.RSLKID.3', '2.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLIKI'),
 'Use information gained from the illustrations and words in a print or digital text to demonstrate understanding of its characters, setting, or plot.'),
('3.RSLIKI.7', '2.RSLIKI.7', '3.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLIKI'),
 'Use information gained from illustrations (e.g., maps, photographs) and the words in a text to demonstrate understanding of the text (e.g., where, when, why, and how key events occur).'),
('4.RSLIKI.7', '4.RSLKID.2', '5.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLIKI'),
 'Make connections between the text of a story or drama and a visual or oral presentation of the text, identifying where each version reflects specific descriptions and directions in the text.'),
('5.RSLIKI.7', '4.RSLIKI.7', '5.RSLIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLIKI'),
 'Analyze how visual and multimedia elements contribute to the meaning, tone, or beauty of a text (e.g., graphic novel, multimedia presentation of fiction, folktale, myth, poem).'),
('K.RSLIKI.9', 'K.RSLIKI.7', '1.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLIKI'),
 'With prompting and support, compare and contrast the adventures and experiences of characters in familiar stories.'),
('1.RSLIKI.9', '1.RSLIKI.7', '1.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLIKI'),
 'Compare and contrast the adventures and experiences of characters in stories.'),
('2.RSLIKI.9', '2.RSLIKI.7', '3.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLIKI'),
 'Compare and contrast two or more versions of the same story (e.g., Cinderella stories) by different authors or from different cultures.'),
('3.RSLIKI.9', '3.RSLIKI.7', '4.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLIKI'),
 'Compare and contrast the most important points and key details presented in two texts on the same topic.'),
('4.RSLIKI.9', '4.RSLRRLTC.10', '5.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLIKI'),
 'Compare and contrast the treatment of similar themes and topics (e.g., opposition of good and evil) and patterns of events (e.g., the quest) in stories, myths, and traditional literature from different cultures.'),
('5.RSLIKI.9', '5.RSLKID.1', '5.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLIKI'),
 'Compare and contrast stories in the same genre (e.g., mysteries and adventure stories) on their approaches to similar themes and topics.'),
('K.RSLRRLTC.10', 'K.RSLKID.1', '1.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSLRRLTC'),
 'Actively engage in group reading activities with purpose and understanding.'),
('1.RSLRRLTC.10', '1.RSLIKI.9', '2.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSLRRLTC'),
 'With prompting and support, read prose and poetry of appropriate complexity for grade 1.'),
('2.RSLRRLTC.10', '1.RSLRRLTC.10', '3.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSLRRLTC'),
 'By the end of the year, read and comprehend literature, including stories and poetry, in the grades 2-3 text complexity band proficiently, with scaffolding as needed at the high end of the range.'),
('3.RSLRRLTC.10', '2.RSLRRLTC.10', '4.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSLRRLTC'),
 'By the end of the year, read and comprehend informational texts, including history/social studies, science, and technical texts, at the high end of the grades 2-3 text complexity band independently and proficiently.'),
('4.RSLRRLTC.10', '3.RSLRRLTC.10', '4.RSLIKI.9',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSLRRLTC'),
 'By the end of the year, read and comprehend literature, including stories, dramas, and poetry, in the grades 4-5 text complexity band proficiently, with scaffolding as needed at the high end of the range.'),
('5.RSLRRLTC.10', '4.RSLRRLTC.10', '5.RSLRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSLRRLTC'),
 'By the end of the year, read and comprehend literature, including stories, dramas, and poetry, at the high end of the grades 4-5 text complexity band independently and proficiently.')
ON CONFLICT (skill_set_code) DO NOTHING;

-- RSIT — Reading: Informational Text
INSERT INTO skill_sets (skill_set_code, prev_skill_set_code, next_skill_set_code, proficiency_id, description) VALUES
('K.RSITKID.1', 'K.RSITKID.1', '1.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITKID'), ''),
('1.RSITKID.1', 'K.RSITKID.1', '2.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITKID'), ''),
('2.RSITKID.1', '1.RSITKID.1', '3.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITKID'), ''),
('3.RSITKID.1', '2.RSITKID.1', '4.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITKID'), ''),
('4.RSITKID.1', '3.RSITKID.1', '5.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITKID'), ''),
('5.RSITKID.1', '4.RSITKID.1', '5.RSITKID.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITKID'), ''),
('K.RSITCS.4', 'K.RSITCS.4', '1.RSITCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITCS'), ''),
('1.RSITCS.4', 'K.RSITCS.4', '2.RSITCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITCS'), ''),
('2.RSITCS.4', '1.RSITCS.4', '3.RSITCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITCS'), ''),
('3.RSITCS.4', '2.RSITCS.4', '4.RSITCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITCS'), ''),
('4.RSITCS.4', '3.RSITCS.4', '5.RSITCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITCS'), ''),
('5.RSITCS.4', '4.RSITCS.4', '5.RSITCS.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITCS'), ''),
('K.RSITIKI.7', 'K.RSITIKI.7', '1.RSITIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITIKI'), ''),
('1.RSITIKI.7', 'K.RSITIKI.7', '2.RSITIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITIKI'), ''),
('2.RSITIKI.7', '1.RSITIKI.7', '3.RSITIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITIKI'), ''),
('3.RSITIKI.7', '2.RSITIKI.7', '4.RSITIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITIKI'), ''),
('4.RSITIKI.7', '3.RSITIKI.7', '5.RSITIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITIKI'), ''),
('5.RSITIKI.7', '4.RSITIKI.7', '5.RSITIKI.7',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITIKI'), ''),
('K.RSITRRLTC.10', 'K.RSITRRLTC.10', '1.RSITRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSITRRLTC'), ''),
('1.RSITRRLTC.10', 'K.RSITRRLTC.10', '2.RSITRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSITRRLTC'), ''),
('2.RSITRRLTC.10', '1.RSITRRLTC.10', '3.RSITRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSITRRLTC'), ''),
('3.RSITRRLTC.10', '2.RSITRRLTC.10', '4.RSITRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSITRRLTC'), ''),
('4.RSITRRLTC.10', '3.RSITRRLTC.10', '5.RSITRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSITRRLTC'), ''),
('5.RSITRRLTC.10', '4.RSITRRLTC.10', '5.RSITRRLTC.10',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSITRRLTC'), '')
ON CONFLICT (skill_set_code) DO NOTHING;

-- RSF — Reading: Foundational Skills
INSERT INTO skill_sets (skill_set_code, prev_skill_set_code, next_skill_set_code, proficiency_id, description) VALUES
('K.RSFSPC.1', 'K.RSFSPC.1', '1.RSFSPC.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFSPC'), ''),
('1.RSFSPC.1', 'K.RSFSPC.1', '1.RSFSPC.1',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFSPC'), ''),
('K.RSFSPA.2', 'K.RSFSPA.2', '1.RSFSPA.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFSPA'), ''),
('1.RSFSPA.2', 'K.RSFSPA.2', '2.RSFSPA.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFSPA'), ''),
('2.RSFSPA.2', '1.RSFSPA.2', '2.RSFSPA.2',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSFSPA'), ''),
('K.RSFPWR.3', 'K.RSFPWR.3', '1.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFPWR'), ''),
('1.RSFPWR.3', 'K.RSFPWR.3', '2.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFPWR'), ''),
('2.RSFPWR.3', '1.RSFPWR.3', '3.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSFPWR'), ''),
('3.RSFPWR.3', '2.RSFPWR.3', '4.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSFPWR'), ''),
('4.RSFPWR.3', '3.RSFPWR.3', '5.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSFPWR'), ''),
('5.RSFPWR.3', '4.RSFPWR.3', '5.RSFPWR.3',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSFPWR'), ''),
('K.RSFF.4', 'K.RSFF.4', '1.RSFF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = 'K.RSFPWR'), ''),
('1.RSFF.4', 'K.RSFF.4', '2.RSFF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '1.RSFPWR'), ''),
('2.RSFF.4', '1.RSFF.4', '3.RSFF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '2.RSFPWR'), ''),
('3.RSFF.4', '2.RSFF.4', '4.RSFF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '3.RSFPWR'), ''),
('4.RSFF.4', '3.RSFF.4', '5.RSFF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '4.RSFPWR'), ''),
('5.RSFF.4', '4.RSFF.4', '5.RSFF.4',
 (SELECT proficiency_id FROM proficiencies WHERE proficiency_code = '5.RSFPWR'), '')
ON CONFLICT (skill_set_code) DO NOTHING;